// Curated family-friendly destinations for autocomplete
export const destinations = [
  // North America
  "New York, NY",
  "San Francisco, CA",
  "Los Angeles, CA",
  "San Diego, CA",
  "Chicago, IL",
  "Washington, DC",
  "Boston, MA",
  "Seattle, WA",
  "Portland, OR",
  "Austin, TX",
  "Denver, CO",
  "Nashville, TN",
  "Orlando, FL",
  "Miami, FL",
  "Honolulu, HI",
  "Maui, HI",
  "Vancouver, Canada",
  "Toronto, Canada",
  "Montreal, Canada",
  "Mexico City, Mexico",
  "Cancun, Mexico",
  "Tulum, Mexico",

  // Europe
  "London, UK",
  "Edinburgh, Scotland",
  "Paris, France",
  "Nice, France",
  "Barcelona, Spain",
  "Madrid, Spain",
  "Rome, Italy",
  "Florence, Italy",
  "Amalfi Coast, Italy",
  "Venice, Italy",
  "Amsterdam, Netherlands",
  "Berlin, Germany",
  "Munich, Germany",
  "Vienna, Austria",
  "Prague, Czech Republic",
  "Lisbon, Portugal",
  "Copenhagen, Denmark",
  "Stockholm, Sweden",
  "Dublin, Ireland",
  "Zurich, Switzerland",
  "Interlaken, Switzerland",
  "Reykjavik, Iceland",
  "Athens, Greece",
  "Santorini, Greece",
  "Dubrovnik, Croatia",

  // Asia
  "Tokyo, Japan",
  "Kyoto, Japan",
  "Osaka, Japan",
  "Seoul, South Korea",
  "Singapore",
  "Bali, Indonesia",
  "Bangkok, Thailand",
  "Chiang Mai, Thailand",
  "Taipei, Taiwan",
  "Hong Kong",
  "Hanoi, Vietnam",
  "Kuala Lumpur, Malaysia",

  // Oceania
  "Sydney, Australia",
  "Melbourne, Australia",
  "Gold Coast, Australia",
  "Auckland, New Zealand",
  "Queenstown, New Zealand",

  // Middle East & Africa
  "Dubai, UAE",
  "Abu Dhabi, UAE",

  // Africa
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  "Kruger National Park, South Africa",
  "Marrakech, Morocco",
  "Casablanca, Morocco",
  "Fez, Morocco",
  "Nairobi, Kenya",
  "Masai Mara, Kenya",
  "Amboseli, Kenya",
  "Mombasa, Kenya",
  "Zanzibar, Tanzania",
  "Serengeti, Tanzania",
  "Arusha, Tanzania",
  "Kilimanjaro, Tanzania",
  "Cairo, Egypt",
  "Luxor, Egypt",
  "Hurghada, Egypt",
  "Kigali, Rwanda",
  "Windhoek, Namibia",
  "Sossusvlei, Namibia",
  "Okavango Delta, Botswana",
  "Chobe, Botswana",
  "Victoria Falls, Zimbabwe",
  "Accra, Ghana",
  "Dakar, Senegal",
  "Addis Ababa, Ethiopia",
  "Lagos, Nigeria",
  "Tunis, Tunisia",
  "Mauritius",
  "Seychelles",

  // Central America & Caribbean
  "San José, Costa Rica",
  "Manuel Antonio, Costa Rica",
  "Arenal, Costa Rica",

  // South America
  "Buenos Aires, Argentina",
  "Rio de Janeiro, Brazil",
  "Sao Paulo, Brazil",
  "Lima, Peru",
  "Cusco, Peru",
  "Machu Picchu, Peru",
  "Bogota, Colombia",
  "Cartagena, Colombia",
  "Medellin, Colombia",
  "Santiago, Chile",
  "Patagonia, Chile",
  "Quito, Ecuador",
  "Galapagos Islands, Ecuador",
]
