-- Private, revocable read-only links for sharing a trip.
-- The share token is a 256-bit capability generated by the application.
create table if not exists public.trip_shares (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  created_by uuid not null references public.profiles(id) on delete cascade,
  token text not null unique check (token ~ '^[A-Za-z0-9_-]{43}$'),
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create unique index if not exists trip_shares_one_active_per_trip
  on public.trip_shares (trip_id)
  where revoked_at is null;

create index if not exists trip_shares_created_by_idx
  on public.trip_shares (created_by);

alter table public.trip_shares enable row level security;

create policy "trip_shares_select_own" on public.trip_shares
  for select using (auth.uid() = created_by);

create policy "trip_shares_insert_own" on public.trip_shares
  for insert with check (
    auth.uid() = created_by
    and exists (
      select 1 from public.trips
      where trips.id = trip_shares.trip_id
        and trips.user_id = auth.uid()
    )
  );

create policy "trip_shares_update_own" on public.trip_shares
  for update using (auth.uid() = created_by)
  with check (
    auth.uid() = created_by
    and exists (
      select 1 from public.trips
      where trips.id = trip_shares.trip_id
        and trips.user_id = auth.uid()
    )
  );

create policy "trip_shares_delete_own" on public.trip_shares
  for delete using (auth.uid() = created_by);

-- Public viewers can only receive the fields required by the read-only trip page.
-- SECURITY DEFINER is intentional: no public table SELECT policy is opened.
create or replace function public.get_shared_trip(p_token text)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'trip', jsonb_build_object(
      'title', trips.title,
      'destination', trips.destination,
      'start_date', trips.start_date,
      'end_date', trips.end_date,
      'accommodation_area', trips.accommodation_area,
      'status', trips.status,
      'itinerary', coalesce(trips.itinerary, '[]'::jsonb)
    ),
    'shared_at', trip_shares.created_at
  )
  from public.trip_shares
  join public.trips
    on trips.id = trip_shares.trip_id
    and trips.user_id = trip_shares.created_by
  where trip_shares.token = p_token
    and trip_shares.revoked_at is null
  limit 1;
$$;

revoke all on function public.get_shared_trip(text) from public;
grant execute on function public.get_shared_trip(text) to anon, authenticated;
